version: '3'

services:
  nodejs-app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  database-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodejs
#   volumes:
#     - /dir/maquina:/var/lib/mysql
